export const STATEMENT = [
  {
    amount: "- $103.56",
    cardKey: 1,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 1,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 2,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 1,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 3,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 4,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 1,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 5,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 6,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 7,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 8,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 9,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 2,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 10,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 1,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 11,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 12,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 13,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 3,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 14,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 3,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 15,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 16,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 17,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 18,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 19,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 3,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 20,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 2,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 21,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 22,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 1,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 23,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 1,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 24,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 3,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 25,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 26,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 27,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 28,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 29,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 1,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 30,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 2,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 31,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 1,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 32,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 3,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 33,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 3,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 34,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 1,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 35,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 36,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 37,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 38,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 39,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 3,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 40,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 1,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 41,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 42,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 43,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 1,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 44,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 2,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 45,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 46,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 47,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 48,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 49,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 3,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 50,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 51,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 52,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 53,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 1,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 54,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 1,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 55,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 56,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 57,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 58,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 59,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 1,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 60,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 1,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 61,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 2,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 62,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 63,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 1,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 64,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 3,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 65,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 66,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 67,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 68,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 69,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 1,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 70,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 1,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 71,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 2,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 72,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 73,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 3,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 74,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 3,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 75,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 76,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 1,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 77,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 78,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 79,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 3,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 80,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 81,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 2,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 82,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 3,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 83,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 84,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 3,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 85,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 86,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 87,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 88,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 89,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 1,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 90,
    title: "Amazon",
  },
  {
    amount: "- $103.56",
    cardKey: 3,
    date: "2024-01-22",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 91,
    title: "Amazon",
  },
  {
    amount: "+ $900.00",
    cardKey: 2,
    date: "2024-01-22",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 92,
    title: "MasterCard",
  },
  {
    amount: "- $20.50",
    cardKey: 3,
    date: "2024-01-20",
    desc: "Products and goods",
    icon: require("../assets/mcdonalds.png"),
    isReplenishment: false,
    key: 93,
    title: "McDonalds",
  },
  {
    amount: "- $87.00",
    cardKey: 2,
    date: "2024-01-20",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 94,
    title: "Apple Inc.",
  },
  {
    amount: "- $13.20",
    cardKey: 2,
    date: "2024-01-18",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 95,
    title: "Starbucks",
  },
  {
    amount: "- $30.45",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Entertainment",
    icon: require("../assets/apple.png"),
    isReplenishment: false,
    key: 96,
    title: "Apple Inc.",
  },
  {
    amount: "- $154.37",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 97,
    title: "Amazon",
  },
  {
    amount: "+ $200.00",
    cardKey: 3,
    date: "2024-01-17",
    desc: "Replenishment card",
    icon: require("../assets/mastercard.png"),
    isReplenishment: true,
    key: 98,
    title: "MasterCard",
  },
  {
    amount: "- $8.30",
    cardKey: 2,
    date: "2024-01-17",
    desc: "Products and goods",
    icon: require("../assets/starbucks.png"),
    isReplenishment: false,
    key: 99,
    title: "Starbucks",
  },
  {
    amount: "- $210.05",
    cardKey: 3,
    date: "2024-01-15",
    desc: "Purchase",
    icon: require("../assets/amazon.png"),
    isReplenishment: false,
    key: 100,
    title: "Amazon",
  },
];
